export interface Country {
  code: string
  flag: string
  name: string
  keywords: string
}

export const countries: Country[] = [
  // 东亚
  { code: "cn", flag: "🇨🇳", name: "中国", keywords: "zhongguo china cn" },
  { code: "hk", flag: "🇭🇰", name: "中国香港", keywords: "zhongguo xianggang hongkong hk" },
  { code: "mo", flag: "🇲🇴", name: "中国澳门", keywords: "zhongguo aomen macau mo" },
  { code: "tw", flag: "🇹🇼", name: "中国台湾", keywords: "zhongguo taiwan tw" },
  { code: "jp", flag: "🇯🇵", name: "日本", keywords: "riben japan jp" },
  { code: "kr", flag: "🇰🇷", name: "韩国", keywords: "hanguo korea kr south korea" },
  { code: "kp", flag: "🇰🇵", name: "朝鲜", keywords: "chaoxian north korea kp" },
  { code: "mn", flag: "🇲🇳", name: "蒙古", keywords: "menggu mongolia mn" },
  // 东南亚
  { code: "sg", flag: "🇸🇬", name: "新加坡", keywords: "xinjiapo singapore sg" },
  { code: "th", flag: "🇹🇭", name: "泰国", keywords: "taiguo thailand th" },
  { code: "vn", flag: "🇻🇳", name: "越南", keywords: "yuenan vietnam vn" },
  { code: "my", flag: "🇲🇾", name: "马来西亚", keywords: "malaixiya malaysia my" },
  { code: "id", flag: "🇮🇩", name: "印度尼西亚", keywords: "yindunixiya indonesia id" },
  { code: "ph", flag: "🇵🇭", name: "菲律宾", keywords: "feilvbin philippines ph" },
  { code: "mm", flag: "🇲🇲", name: "缅甸", keywords: "miandian myanmar mm" },
  { code: "kh", flag: "🇰🇭", name: "柬埔寨", keywords: "jianpuzhai cambodia kh" },
  { code: "la", flag: "🇱🇦", name: "老挝", keywords: "laowo laos la" },
  { code: "bn", flag: "🇧🇳", name: "文莱", keywords: "wenlai brunei bn" },
  { code: "tl", flag: "🇹🇱", name: "东帝汶", keywords: "dongdiwen timor-leste tl east timor" },
  // 南亚
  { code: "in", flag: "🇮🇳", name: "印度", keywords: "yindu india in" },
  { code: "pk", flag: "🇵🇰", name: "巴基斯坦", keywords: "bajisitan pakistan pk" },
  { code: "bd", flag: "🇧🇩", name: "孟加拉国", keywords: "mengjialaguo bangladesh bd" },
  { code: "lk", flag: "🇱🇰", name: "斯里兰卡", keywords: "sililanka sri lanka lk" },
  { code: "np", flag: "🇳🇵", name: "尼泊尔", keywords: "niboer nepal np" },
  { code: "bt", flag: "🇧🇹", name: "不丹", keywords: "budan bhutan bt" },
  { code: "mv", flag: "🇲🇻", name: "马尔代夫", keywords: "maerdaifu maldives mv" },
  // 中亚
  { code: "kz", flag: "🇰🇿", name: "哈萨克斯坦", keywords: "hasakesitan kazakhstan kz" },
  { code: "uz", flag: "🇺🇿", name: "乌兹别克斯坦", keywords: "wuzibiekesitan uzbekistan uz" },
  { code: "tm", flag: "🇹🇲", name: "土库曼斯坦", keywords: "tukumansitan turkmenistan tm" },
  { code: "kg", flag: "🇰🇬", name: "吉尔吉斯斯坦", keywords: "jierjisisitan kyrgyzstan kg" },
  { code: "tj", flag: "🇹🇯", name: "塔吉克斯坦", keywords: "tajikesitan tajikistan tj" },
  // 西亚 / 中东
  { code: "tr", flag: "🇹🇷", name: "土耳其", keywords: "tuerqi turkey tr türkiye" },
  { code: "ae", flag: "🇦🇪", name: "阿联酋", keywords: "alianqiu uae united arab emirates ae dubai" },
  { code: "sa", flag: "🇸🇦", name: "沙特阿拉伯", keywords: "shate alabo saudi arabia sa" },
  { code: "il", flag: "🇮🇱", name: "以色列", keywords: "yiselie israel il" },
  { code: "ir", flag: "🇮🇷", name: "伊朗", keywords: "yilang iran ir" },
  { code: "iq", flag: "🇮🇶", name: "伊拉克", keywords: "yilake iraq iq" },
  { code: "kw", flag: "🇰🇼", name: "科威特", keywords: "keweite kuwait kw" },
  { code: "qa", flag: "🇶🇦", name: "卡塔尔", keywords: "kataer qatar qa" },
  { code: "bh", flag: "🇧🇭", name: "巴林", keywords: "balin bahrain bh" },
  { code: "om", flag: "🇴🇲", name: "阿曼", keywords: "aman oman om" },
  { code: "ye", flag: "🇾🇪", name: "也门", keywords: "yemen ye" },
  { code: "jo", flag: "🇯🇴", name: "约旦", keywords: "yuedan jordan jo" },
  { code: "lb", flag: "🇱🇧", name: "黎巴嫩", keywords: "libanen lebanon lb" },
  { code: "sy", flag: "🇸🇾", name: "叙利亚", keywords: "xuliya syria sy" },
  { code: "ps", flag: "🇵🇸", name: "巴勒斯坦", keywords: "balesitan palestine ps" },
  { code: "cy", flag: "🇨🇾", name: "塞浦路斯", keywords: "saipulusi cyprus cy" },
  { code: "ge", flag: "🇬🇪", name: "格鲁吉亚", keywords: "gelujiya georgia ge" },
  { code: "am", flag: "🇦🇲", name: "亚美尼亚", keywords: "yameiniya armenia am" },
  { code: "az", flag: "🇦🇿", name: "阿塞拜疆", keywords: "asaibaijiang azerbaijan az" },
  { code: "af", flag: "🇦🇫", name: "阿富汗", keywords: "afuhan afghanistan af" },
  // 欧洲 - 西欧
  { code: "gb", flag: "🇬🇧", name: "英国", keywords: "yingguo uk gb united kingdom britain" },
  { code: "fr", flag: "🇫🇷", name: "法国", keywords: "faguo france fr" },
  { code: "de", flag: "🇩🇪", name: "德国", keywords: "deguo germany de" },
  { code: "nl", flag: "🇳🇱", name: "荷兰", keywords: "helan netherlands nl holland" },
  { code: "be", flag: "🇧🇪", name: "比利时", keywords: "bilishi belgium be" },
  { code: "lu", flag: "🇱🇺", name: "卢森堡", keywords: "lusenbao luxembourg lu" },
  { code: "ie", flag: "🇮🇪", name: "爱尔兰", keywords: "aierlan ireland ie" },
  { code: "ch", flag: "🇨🇭", name: "瑞士", keywords: "ruishi switzerland ch" },
  { code: "at", flag: "🇦🇹", name: "奥地利", keywords: "aodili austria at" },
  { code: "li", flag: "🇱🇮", name: "列支敦士登", keywords: "liezhidunshideng liechtenstein li" },
  { code: "mc", flag: "🇲🇨", name: "摩纳哥", keywords: "monage monaco mc" },
  // 欧洲 - 南欧
  { code: "es", flag: "🇪🇸", name: "西班牙", keywords: "xibanya spain es" },
  { code: "pt", flag: "🇵🇹", name: "葡萄牙", keywords: "putaoya portugal pt" },
  { code: "it", flag: "🇮🇹", name: "意大利", keywords: "yidali italy it" },
  { code: "gr", flag: "🇬🇷", name: "希腊", keywords: "xila greece gr" },
  { code: "mt", flag: "🇲🇹", name: "马耳他", keywords: "maerta malta mt" },
  { code: "ad", flag: "🇦🇩", name: "安道尔", keywords: "andaoer andorra ad" },
  { code: "sm", flag: "🇸🇲", name: "圣马力诺", keywords: "shengmalinuo san marino sm" },
  { code: "va", flag: "🇻🇦", name: "梵蒂冈", keywords: "fandigang vatican va" },
  // 欧洲 - 北欧
  { code: "se", flag: "🇸🇪", name: "瑞典", keywords: "ruidian sweden se" },
  { code: "no", flag: "🇳🇴", name: "挪威", keywords: "nuowei norway no" },
  { code: "fi", flag: "🇫🇮", name: "芬兰", keywords: "fenlan finland fi" },
  { code: "dk", flag: "🇩🇰", name: "丹麦", keywords: "danmai denmark dk" },
  { code: "is", flag: "🇮🇸", name: "冰岛", keywords: "bingdao iceland is" },
  // 欧洲 - 东欧
  { code: "ru", flag: "🇷🇺", name: "俄罗斯", keywords: "eluosi russia ru" },
  { code: "pl", flag: "🇵🇱", name: "波兰", keywords: "bolan poland pl" },
  { code: "ua", flag: "🇺🇦", name: "乌克兰", keywords: "wukelan ukraine ua" },
  { code: "ro", flag: "🇷🇴", name: "罗马尼亚", keywords: "luomaniya romania ro" },
  { code: "bg", flag: "🇧🇬", name: "保加利亚", keywords: "baojialiya bulgaria bg" },
  { code: "hu", flag: "🇭🇺", name: "匈牙利", keywords: "xiongyali hungary hu" },
  { code: "cz", flag: "🇨🇿", name: "捷克", keywords: "jieke czech cz czechia" },
  { code: "sk", flag: "🇸🇰", name: "斯洛伐克", keywords: "siluofake slovakia sk" },
  { code: "hr", flag: "🇭🇷", name: "克罗地亚", keywords: "keluodiya croatia hr" },
  { code: "si", flag: "🇸🇮", name: "斯洛文尼亚", keywords: "siluowenniya slovenia si" },
  { code: "rs", flag: "🇷🇸", name: "塞尔维亚", keywords: "saierweiya serbia rs" },
  { code: "me", flag: "🇲🇪", name: "黑山", keywords: "heishan montenegro me" },
  { code: "mk", flag: "🇲🇰", name: "北马其顿", keywords: "beimaqidun north macedonia mk" },
  { code: "al", flag: "🇦🇱", name: "阿尔巴尼亚", keywords: "aerbaniya albania al" },
  { code: "ba", flag: "🇧🇦", name: "波黑", keywords: "bohei bosnia herzegovina ba" },
  { code: "xk", flag: "🇽🇰", name: "科索沃", keywords: "kesuowo kosovo xk" },
  { code: "md", flag: "🇲🇩", name: "摩尔多瓦", keywords: "moerduowa moldova md" },
  { code: "by", flag: "🇧🇾", name: "白俄罗斯", keywords: "baieluosi belarus by" },
  // 欧洲 - 波罗的海
  { code: "lt", flag: "🇱🇹", name: "立陶宛", keywords: "litaowan lithuania lt" },
  { code: "lv", flag: "🇱🇻", name: "拉脱维亚", keywords: "latuoweiya latvia lv" },
  { code: "ee", flag: "🇪🇪", name: "爱沙尼亚", keywords: "aishaniya estonia ee" },
  // 北美
  { code: "us", flag: "🇺🇸", name: "美国", keywords: "meiguo usa us united states america" },
  { code: "ca", flag: "🇨🇦", name: "加拿大", keywords: "jianada canada ca" },
  { code: "mx", flag: "🇲🇽", name: "墨西哥", keywords: "moxige mexico mx" },
  // 中美洲 & 加勒比
  { code: "pa", flag: "🇵🇦", name: "巴拿马", keywords: "banama panama pa" },
  { code: "cr", flag: "🇨🇷", name: "哥斯达黎加", keywords: "gesidalijia costa rica cr" },
  { code: "gt", flag: "🇬🇹", name: "危地马拉", keywords: "weidimala guatemala gt" },
  { code: "hn", flag: "🇭🇳", name: "洪都拉斯", keywords: "hongdulasi honduras hn" },
  { code: "sv", flag: "🇸🇻", name: "萨尔瓦多", keywords: "saerwaduo el salvador sv" },
  { code: "ni", flag: "🇳🇮", name: "尼加拉瓜", keywords: "nijialagua nicaragua ni" },
  { code: "bz", flag: "🇧🇿", name: "伯利兹", keywords: "bolizi belize bz" },
  { code: "cu", flag: "🇨🇺", name: "古巴", keywords: "guba cuba cu" },
  { code: "jm", flag: "🇯🇲", name: "牙买加", keywords: "yamaijia jamaica jm" },
  { code: "ht", flag: "🇭🇹", name: "海地", keywords: "haidi haiti ht" },
  { code: "do", flag: "🇩🇴", name: "多米尼加", keywords: "duominijia dominican republic do" },
  { code: "tt", flag: "🇹🇹", name: "特立尼达和多巴哥", keywords: "telinida duobage trinidad tobago tt" },
  { code: "bs", flag: "🇧🇸", name: "巴哈马", keywords: "bahama bahamas bs" },
  { code: "bb", flag: "🇧🇧", name: "巴巴多斯", keywords: "babaduosi barbados bb" },
  { code: "pr", flag: "🇵🇷", name: "波多黎各", keywords: "boduolige puerto rico pr" },
  // 南美
  { code: "br", flag: "🇧🇷", name: "巴西", keywords: "baxi brazil br" },
  { code: "ar", flag: "🇦🇷", name: "阿根廷", keywords: "agenting argentina ar" },
  { code: "cl", flag: "🇨🇱", name: "智利", keywords: "zhili chile cl" },
  { code: "co", flag: "🇨🇴", name: "哥伦比亚", keywords: "gelunbiya colombia co" },
  { code: "pe", flag: "🇵🇪", name: "秘鲁", keywords: "bilu peru pe" },
  { code: "ve", flag: "🇻🇪", name: "委内瑞拉", keywords: "weineiruila venezuela ve" },
  { code: "ec", flag: "🇪🇨", name: "厄瓜多尔", keywords: "eguaduoer ecuador ec" },
  { code: "bo", flag: "🇧🇴", name: "玻利维亚", keywords: "boliweiya bolivia bo" },
  { code: "py", flag: "🇵🇾", name: "巴拉圭", keywords: "balagui paraguay py" },
  { code: "uy", flag: "🇺🇾", name: "乌拉圭", keywords: "wulagui uruguay uy" },
  { code: "gy", flag: "🇬🇾", name: "圭亚那", keywords: "guiyana guyana gy" },
  { code: "sr", flag: "🇸🇷", name: "苏里南", keywords: "sulinan suriname sr" },
  // 大洋洲
  { code: "au", flag: "🇦🇺", name: "澳大利亚", keywords: "aodaliya australia au" },
  { code: "nz", flag: "🇳🇿", name: "新西兰", keywords: "xinxilan new zealand nz" },
  { code: "pg", flag: "🇵🇬", name: "巴布亚新几内亚", keywords: "babuyaxinjineiya papua new guinea pg" },
  { code: "fj", flag: "🇫🇯", name: "斐济", keywords: "feiji fiji fj" },
  { code: "ws", flag: "🇼🇸", name: "萨摩亚", keywords: "samoya samoa ws" },
  { code: "to", flag: "🇹🇴", name: "汤加", keywords: "tangjia tonga to" },
  { code: "vu", flag: "🇻🇺", name: "瓦努阿图", keywords: "wanuatu vanuatu vu" },
  { code: "gu", flag: "🇬🇺", name: "关岛", keywords: "guandao guam gu" },
  { code: "nc", flag: "🇳🇨", name: "新喀里多尼亚", keywords: "xinkaliduoniya new caledonia nc" },
  { code: "pf", flag: "🇵🇫", name: "法属波利尼西亚", keywords: "fashu bolinixiya french polynesia pf tahiti" },
  // 非洲 - 北非
  { code: "eg", flag: "🇪🇬", name: "埃及", keywords: "aiji egypt eg" },
  { code: "ma", flag: "🇲🇦", name: "摩洛哥", keywords: "moluoge morocco ma" },
  { code: "tn", flag: "🇹🇳", name: "突尼斯", keywords: "tunisi tunisia tn" },
  { code: "dz", flag: "🇩🇿", name: "阿尔及利亚", keywords: "aerjiliya algeria dz" },
  { code: "ly", flag: "🇱🇾", name: "利比亚", keywords: "libiya libya ly" },
  { code: "sd", flag: "🇸🇩", name: "苏丹", keywords: "sudan sd" },
  // 非洲 - 西非
  { code: "ng", flag: "🇳🇬", name: "尼日利亚", keywords: "niriliya nigeria ng" },
  { code: "gh", flag: "🇬🇭", name: "加纳", keywords: "jiana ghana gh" },
  { code: "sn", flag: "🇸🇳", name: "塞内加尔", keywords: "saineijiaer senegal sn" },
  { code: "ci", flag: "🇨🇮", name: "科特迪瓦", keywords: "ketediwa ivory coast cote divoire ci" },
  { code: "ml", flag: "🇲🇱", name: "马里", keywords: "mali ml" },
  { code: "bf", flag: "🇧🇫", name: "布基纳法索", keywords: "bujinafasuo burkina faso bf" },
  { code: "ne", flag: "🇳🇪", name: "尼日尔", keywords: "nirier niger ne" },
  { code: "gn", flag: "🇬🇳", name: "几内亚", keywords: "jineiya guinea gn" },
  { code: "tg", flag: "🇹🇬", name: "多哥", keywords: "duoge togo tg" },
  { code: "bj", flag: "🇧🇯", name: "贝宁", keywords: "beining benin bj" },
  { code: "sl", flag: "🇸🇱", name: "塞拉利昂", keywords: "sailaliang sierra leone sl" },
  { code: "lr", flag: "🇱🇷", name: "利比里亚", keywords: "libiliya liberia lr" },
  { code: "mr", flag: "🇲🇷", name: "毛里塔尼亚", keywords: "maolitaniya mauritania mr" },
  { code: "gm", flag: "🇬🇲", name: "冈比亚", keywords: "gangbiya gambia gm" },
  { code: "gw", flag: "🇬🇼", name: "几内亚比绍", keywords: "jineiya bisao guinea-bissau gw" },
  { code: "cv", flag: "🇨🇻", name: "佛得角", keywords: "fodejiao cape verde cv" },
  // 非洲 - 东非
  { code: "ke", flag: "🇰🇪", name: "肯尼亚", keywords: "kenniya kenya ke" },
  { code: "et", flag: "🇪🇹", name: "埃塞俄比亚", keywords: "aisaiebiya ethiopia et" },
  { code: "tz", flag: "🇹🇿", name: "坦桑尼亚", keywords: "tansangniya tanzania tz" },
  { code: "ug", flag: "🇺🇬", name: "乌干达", keywords: "wuganda uganda ug" },
  { code: "rw", flag: "🇷🇼", name: "卢旺达", keywords: "luwangda rwanda rw" },
  { code: "bi", flag: "🇧🇮", name: "布隆迪", keywords: "bulongdi burundi bi" },
  { code: "so", flag: "🇸🇴", name: "索马里", keywords: "suomali somalia so" },
  { code: "dj", flag: "🇩🇯", name: "吉布提", keywords: "jibuti djibouti dj" },
  { code: "er", flag: "🇪🇷", name: "厄立特里亚", keywords: "eliteliya eritrea er" },
  { code: "mg", flag: "🇲🇬", name: "马达加斯加", keywords: "madajiasijia madagascar mg" },
  { code: "mu", flag: "🇲🇺", name: "毛里求斯", keywords: "maoliqiusi mauritius mu" },
  { code: "sc", flag: "🇸🇨", name: "塞舌尔", keywords: "saishe'er seychelles sc" },
  { code: "km", flag: "🇰🇲", name: "科摩罗", keywords: "kemoluo comoros km" },
  // 非洲 - 中非
  { code: "cd", flag: "🇨🇩", name: "刚果（金）", keywords: "gangguo congo kinshasa cd drc" },
  { code: "cg", flag: "🇨🇬", name: "刚果（布）", keywords: "gangguo congo brazzaville cg" },
  { code: "cm", flag: "🇨🇲", name: "喀麦隆", keywords: "kamailong cameroon cm" },
  { code: "ga", flag: "🇬🇦", name: "加蓬", keywords: "jiapeng gabon ga" },
  { code: "td", flag: "🇹🇩", name: "乍得", keywords: "zhade chad td" },
  { code: "cf", flag: "🇨🇫", name: "中非", keywords: "zhongfei central african republic cf" },
  { code: "gq", flag: "🇬🇶", name: "赤道几内亚", keywords: "chidao jineiya equatorial guinea gq" },
  { code: "st", flag: "🇸🇹", name: "圣多美和普林西比", keywords: "shengduomei pulinxibi sao tome principe st" },
  // 非洲 - 南非
  { code: "za", flag: "🇿🇦", name: "南非", keywords: "nanfei south africa za" },
  { code: "zw", flag: "🇿🇼", name: "津巴布韦", keywords: "jinbabuwei zimbabwe zw" },
  { code: "zm", flag: "🇿🇲", name: "赞比亚", keywords: "zanbiya zambia zm" },
  { code: "mz", flag: "🇲🇿", name: "莫桑比克", keywords: "mosangbike mozambique mz" },
  { code: "bw", flag: "🇧🇼", name: "博茨瓦纳", keywords: "bociwana botswana bw" },
  { code: "na", flag: "🇳🇦", name: "纳米比亚", keywords: "namibiya namibia na" },
  { code: "ao", flag: "🇦🇴", name: "安哥拉", keywords: "angela angola ao" },
  { code: "mw", flag: "🇲🇼", name: "马拉维", keywords: "malawei malawi mw" },
  { code: "ls", flag: "🇱🇸", name: "莱索托", keywords: "laisuotuo lesotho ls" },
  { code: "sz", flag: "🇸🇿", name: "斯威士兰", keywords: "siweishilan eswatini sz swaziland" },
]

export function searchCountries(keyword: string): Country[] {
  if (!keyword) return countries
  const lower = keyword.toLowerCase()
  return countries.filter(
    (c) => c.name.includes(keyword) || c.keywords.includes(lower) || c.flag === keyword
  )
}
